version: '3'

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./envs/.postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:6.2.5-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: im_survey_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - ./envs/.web
    # environment:
    #   - RAILS_ENV=test
    stdin_open: true
    tty: true

volumes:
  redis:
  pg_data: